trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install
  displayName: 'Install npm dependencies'

- script: apt-get install -y chrome
  displayName: 'Install Chrome for testing'

- script: npm run lint
  displayName: 'Run lint'

- script: npm run test
  displayName: 'Run tests'
