trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: npm install
  displayName: 'Install npm dependencies'

- script: npm run lint
  displayName: 'Run lint'

- script: npm run test
  displayName: 'Run tests'
