name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install --legacy-peer-deps
      - run: npm run lint
      - run: npm run test
